//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniSchedule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCongGiangDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhanCongGiangDay()
        {
            this.LichDays = new HashSet<LichDay>();
        }
    
        public int MaPhanCong { get; set; }
        public string MaGV { get; set; }
        public string MaLHP { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> HocKi { get; set; }
        public string NamHoc { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichDay> LichDays { get; set; }
        public virtual LopHocPhan LopHocPhan { get; set; }
    }
}
